language: node_js
node_js:
  - '12'
sudo: false
cache:
  directories:
  - node_modules
git:
  depth: 1
install:
- npm ci
script:
- npm run build
after_success:
- npm run semantic-release
env:
  global:
  - secure: b816T9d1PjgnfxRfUcwU5BRzj9HWm0CkgX4wPJWZKhu3S0kOlBKj8J2UKVEchV5etA+T26XYhcfkI1AXZlLDrjTGkdoCzBLp/r3C2NJtdbO6CNR0vVT5FeZMFJC+JrSKFWzwdj305An2+S4EUe/gwlII+nWfK3zpHEqkfsYg1XuXDfYNNf4WmSq8SNUq71FXYGCltUJd6JjbSF5YfwJXcxdYBLtvju0f0keYyGiZO0XSQgIRVKqDtGDmQMvW/BjH2+5ENg0VzK63yDjByZXkkajrlNZBEb5g7CjpLQZv8tdFnWfXZ1rS9spiiat1N0cor4So4LwQftqcLiVyYsoIJJXDQUWGqqoMrf7dXK508pQqIpBNoougle6h2nErhypUmhvePE0Fq4THhne2fEEbHSRWKlC6jfQIf4gs2oqxODRC9kZUJ4yMeTVdvV4k9EU2XJI31SOAfJUP9B0MJunx8f9vflKSH/P5EgP8uYXXxegXCkmVzy+3cIkXnBGjy/XhySstJmgTnQx+vRbZHN6VRpJ4MDGjxFx3JEHL5T+ykS+YgSPIv6K0QYt21BGUg30aTahuWKKG5k6EnPXAj75wFtHMOmGCVsVSy2XLMKm7LWL3BH3SvFzoLcbqYgREUmMrhT2Ae2XoXR+knTiosjk5H8uC4PuRBf/d9tbr4yl9CAM=
  - secure: OViNOjWtNT7xkhE2g6hdZ+dL0QB9vK5lKhTC0EhJdmHXJVYGypcuqA/ivJooktA/cTMgQ/2aYX1kW3zzQHcYKOz2RzotmEs4YB7/+cNoRF2C/hBEdjgSvjfO/4Eg7PyDrZDZIBbRphEKXFUD+cBTcmTahVlGYoCoLPJ2slbx/wxxdPX9MlAPqK+ewn+u7yCiH5wfr5ux90vMGhpZfGg9CCHf9KY6IE3JBRp1XCfiX/CVOv97Dstpz3sWjuxsRSmfNz1QF1r9b2JRhFYrkyryMyvW/ZudfKZkTYez8cakfUr4r08LROyBzSr/+votvSZ6fT091H15RcMwB1uPLQg1uWcGMn0NWI7/60BycX7DK34h6pmdjx0phClREPOsXfheJq+h3nL7Jjq5FQ9A7gIRnBAtX7oxucbY8cgkRqVQiZsJQD59mj842w7To2eCyD44RgctVKL5nHIPfXS5Wt5j9JSNBjLLvWSp+QCGVpWCP0yl+EbEg8xbjFwruk4Lhv4epcucqetO9+lFXBYxa2XuTBtXq8tNt7zUQ2tr+Y6rwt+btvhSzyqwfxWcDmJd9zOJPxBsNdVGEFmFg8teWBpYd6el58FCKsfkRdn5DdlR5hidU3zudYhXP8d7XA1gDNtFvKwfCa+SraOjOxUxeRXHU2FfTtNc97GbQTq0hm8vcuk=
