language: node_js
node_js:
- stable
sudo: false
cache:
  directories:
  - node_modules
git:
  depth: 1
install:
- npm install
script:
- npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: dvabuzyarov@gmail.com
  api_key:
    secure: LNa4XgzL0cCAHqLKasN0biwDAl5z5TP6ffVFSmZxNQcPkYPPaLamNup/krZcxfdcR6NliYSN/MrhVVKsBEe+iWUEfRNyvvmDamxpxwGpO2FfmU+To+9DHrgnP5LmYu7WRwj47LTZnfPrPBHU8fIeTB+wg0KK3Kfds3+0IdixoMzTUqOn3sUWQ7hkKuz3K09XD38nt3jZbSTWI65Y2PFvBewXBhfOLAkbVDHrD6KZziUiOQyq0TtbOoHHC2QuGu5rV7ufMz+wwL64vcxFG/Y/pAah+aXg/HoAtrkaWIwcNTJTzCJJwBI/H7prYsg2JTzqGaT3m03i8ZweTThrJrc3TU81Ygs9h2F6JosZq+DbC5Rlpuvq3Y6fwFfEA2oRqrSe7siECT2HFNY3Q35/bk34Hxq86F4jDnR2Eie/XeQ8ze0R9x0/FaVMSVqliEh5/FrPUu3Rz5YecACwZ/Q3NObXskMNx/1e9J90CTwxRol2HPOC+DJz1OnG2aAWN9lk3tST0goInMnOWLVQquHYbgU4aQ/iABBPuZLPrvsC9guJfjBp6e/O4AlvhwdOfVNLnx1OF4Df0GPLrZM8QrfaYhFkPU6X81Apu8JXTDs+FYSC7Z3XZqvWovz8tPSxw0q4GVYPkDFq3+fRUIl7sp1JijMTeUGgcYKJNMhW0EUMSmgK7ss=
  on:
    tags: true
    repo: dvabuzyarov/product-version
env:
  global:
    secure: b816T9d1PjgnfxRfUcwU5BRzj9HWm0CkgX4wPJWZKhu3S0kOlBKj8J2UKVEchV5etA+T26XYhcfkI1AXZlLDrjTGkdoCzBLp/r3C2NJtdbO6CNR0vVT5FeZMFJC+JrSKFWzwdj305An2+S4EUe/gwlII+nWfK3zpHEqkfsYg1XuXDfYNNf4WmSq8SNUq71FXYGCltUJd6JjbSF5YfwJXcxdYBLtvju0f0keYyGiZO0XSQgIRVKqDtGDmQMvW/BjH2+5ENg0VzK63yDjByZXkkajrlNZBEb5g7CjpLQZv8tdFnWfXZ1rS9spiiat1N0cor4So4LwQftqcLiVyYsoIJJXDQUWGqqoMrf7dXK508pQqIpBNoougle6h2nErhypUmhvePE0Fq4THhne2fEEbHSRWKlC6jfQIf4gs2oqxODRC9kZUJ4yMeTVdvV4k9EU2XJI31SOAfJUP9B0MJunx8f9vflKSH/P5EgP8uYXXxegXCkmVzy+3cIkXnBGjy/XhySstJmgTnQx+vRbZHN6VRpJ4MDGjxFx3JEHL5T+ykS+YgSPIv6K0QYt21BGUg30aTahuWKKG5k6EnPXAj75wFtHMOmGCVsVSy2XLMKm7LWL3BH3SvFzoLcbqYgREUmMrhT2Ae2XoXR+knTiosjk5H8uC4PuRBf/d9tbr4yl9CAM=
