language: node_js
node_js:
- '12'
sudo: false
cache:
  directories:
    - "$HOME/.npm"
git:
  depth: 1
install:
- npm ci
script:
- npm run build
after_success:
- npm run semantic-release
env:
  global:
  - secure: SKvAv92+miyS0xGclDPKWtM6ZzAHMtrtA6feJX07SPx+NBUwPJ8UTrlookE+tR0FosxyYEu+rWaBVwAOsV3burggapcrc4FjzcC307l9iFoFYzuuagqoGGYtkVnb3gmhLUFplVH0gV8s8SsoK2IVydMjYPXSqF4OBxO+NMjPuvGBwfzh7/DCpRaRWtgFIpntA1Hj9bBZz25zyPnoUPbPTJu4+rQJqUlP4ka3ieJZ6tPP6g8sN0fhDllb7TiKO+ZzcbmWvkA0snHTs93FZXYfoLAB21d05hM6c8PnzfTXxmjx16hDzI5Yb1Gam17rj9JGngZywmxZlSej/1dzlL8LRJjLNqAdaTRLQhLUIEQWvfyLEW30OK52F7EibQZh5HE9Cd2Gth2VdQO4EjA9eFWLnEppXfbY822BewSoPiHx0cHcBPoHLYErQuA06UTn8wrka9kAXUB3/cWbNjD9GFp8R+PCXuqQZv3X7kBkB00pefNHfR1PSPemwSQSH6Rzc9/hW8pfH3A1tSaebZ/RmwmCdG/g5DSudDAnXVudgUcjqRQIqFHXQlfq5xDszaU57wwgP5V20K8B4qKPH+qe+hss4YthNTp5PTk3zT+oPaRalSmMMXSh56FuucBQAcCWHYHFloUQusxCz3l5DWAmUR+/5Le3xQHeGrft210IcB0LLYE=
  - secure: Hi+4C4nBwNg8Ww8fevQC+Mxg1oFfIv9MYQCYaAiyhuStC6k0EXWoO+rRT/wIcHCsEixpvXNUH8oH4wDQw5JWRqiOg3jjRa/KJOhgLzTQFGS8gz9ZrmQEL/UNfgccNGoS1I/IU0b+Q5XuSHQRo7xItRDRz3Z5KedHQKSvbUX4Rzo1I4HoBByyvou/xRLPWkjBh0siE6EQ+GONTnlOl+RM7CpD4oLslel5MyBplJFPqyEir7H5EDX1X7Z0EpzN5HN6rWjEhX1oY73ioVBB+Q9X/j9zbY4NsBvwM9HgDrK3lppeTxAZ0aN16p/JqQXBJA/AlVSWkqx4MJyFI5E73XYsfi3DYJ6FszG5Ksq/q8+LcQ3W7lqc8z5z12sqY+ug5WOIPYLwv+g8ealStxo8FEqWSU9P+nTRg/CwvEdR4acQtbetAVZe9sp12AVTqBXPZlqOyXLTYu9RLfRx8YiXJzlGXqVFxG/f1v8J2MEhm2fPGV+9FAULNT8iqL+pWDWjIXxn3MhHcCzM9PSM0BTF1UnZi2RuoRpVtxK3sVQmT4JMQP2bFj195bgmMsj6aQH5ycsovDU3bfrIg+ra1qrTz1NSXiy5zBHkCKKDCPoicH/ir1PZzso8kzRYs7jjQf1c34p87EQt+hIipOYFYLwTSmXgWlNXu8mbZBDaZCFCJeIbMis=
